//! License verification SDK for AuthorizationTool.
//!
//! Verifies license codes generated by AuthorizationTool using
//! ECDSA P-256 signature verification (public key only).

use base64::Engine;
use p256::ecdsa::{Signature, VerifyingKey};
use p256::elliptic_curve::sec1::FromEncodedPoint;
use p256::{EncodedPoint, PublicKey};
use sha2::{Digest, Sha256};
use serde::Serialize;

/// License info extracted from a license code.
#[derive(Debug, Clone, Serialize)]
pub struct LicenseInfo {
    /// Hardware ID from request code.
    pub hardware_id: String,
    /// Application time as Unix timestamp.
    pub apply_timestamp: i64,
    /// Product name (UTF-8).
    pub product_name: String,
    /// Expiry time as Unix timestamp.
    pub expiry_timestamp: i64,
}

/// Possible errors during license verification.
#[derive(Debug)]
pub enum VerifyError {
    /// Base64 decoding failed.
    Base64Error(String),
    /// License code data is too short or malformed.
    InvalidFormat(String),
    /// Failed to parse the public key file.
    InvalidPublicKey(String),
    /// ECDSA signature verification failed.
    SignatureError(String),
}

impl std::fmt::Display for VerifyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            VerifyError::Base64Error(e) => write!(f, "Base64 decode error: {}", e),
            VerifyError::InvalidFormat(e) => write!(f, "Invalid format: {}", e),
            VerifyError::InvalidPublicKey(e) => write!(f, "Invalid public key: {}", e),
            VerifyError::SignatureError(e) => write!(f, "Signature error: {}", e),
        }
    }
}

impl std::error::Error for VerifyError {}

/// BCRYPT_ECCKEY_BLOB magic number for ECDSA P-256 public key.
const BCRYPT_ECDSA_PUBLIC_P256_MAGIC: u32 = 0x31534345; // "ECS1"

/// Parse a Windows BCRYPT_ECCPUBLIC_BLOB (P-256) and extract the public key.
///
/// BCRYPT_ECCPUBLIC_BLOB layout:
/// ```text
/// [4 bytes magic] [4 bytes cbKey=32] [32 bytes X] [32 bytes Y]
/// ```
fn parse_public_key(blob: &[u8]) -> Result<VerifyingKey, VerifyError> {
    if blob.len() < 8 {
        return Err(VerifyError::InvalidPublicKey("public key blob too short".into()));
    }
    let magic = u32::from_le_bytes(blob[0..4].try_into().unwrap());
    if magic != BCRYPT_ECDSA_PUBLIC_P256_MAGIC {
        return Err(VerifyError::InvalidPublicKey(format!(
            "wrong magic: 0x{:08X}, expected 0x{:08X}",
            magic, BCRYPT_ECDSA_PUBLIC_P256_MAGIC
        )));
    }
    let cb_key = u32::from_le_bytes(blob[4..8].try_into().unwrap()) as usize;
    if cb_key != 32 {
        return Err(VerifyError::InvalidPublicKey(format!(
            "unexpected key length: {}, expected 32",
            cb_key
        )));
    }
    let expected_len = 8 + cb_key * 2;
    if blob.len() < expected_len {
        return Err(VerifyError::InvalidPublicKey("public key blob truncated".into()));
    }

    // Build SEC1 uncompressed point: 0x04 + X + Y
    let x = &blob[8..8 + cb_key];
    let y = &blob[8 + cb_key..8 + cb_key * 2];
    let mut sec1 = vec![0x04];
    sec1.extend_from_slice(x);
    sec1.extend_from_slice(y);

    let encoded = EncodedPoint::from_bytes(&sec1)
        .map_err(|e| VerifyError::InvalidPublicKey(format!("invalid SEC1 point: {}", e)))?;
    let pub_key = PublicKey::from_encoded_point(&encoded)
        .into_option()
        .ok_or_else(|| VerifyError::InvalidPublicKey("invalid public key point".into()))?;

    Ok(VerifyingKey::from(pub_key))
}

/// Deserialize license data: hlen(4) + hardware_id + apply(8) + name_len(4) + name + expiry(8)
fn deserialize_license(data: &[u8]) -> Result<LicenseInfo, VerifyError> {
    if data.len() < 24 {
        return Err(VerifyError::InvalidFormat("license data too short".into()));
    }
    let mut off = 0usize;

    // hardware_id
    let hlen = u32::from_le_bytes(data[off..off + 4].try_into().unwrap()) as usize;
    off += 4;
    if data.len() < off + hlen {
        return Err(VerifyError::InvalidFormat("hardware id truncated".into()));
    }
    let hardware_id = String::from_utf8(data[off..off + hlen].to_vec())
        .map_err(|e| VerifyError::InvalidFormat(format!("invalid UTF-8 hardware id: {}", e)))?;
    off += hlen;

    // apply_timestamp
    if data.len() < off + 8 {
        return Err(VerifyError::InvalidFormat("apply timestamp truncated".into()));
    }
    let apply_timestamp = i64::from_le_bytes(data[off..off + 8].try_into().unwrap());
    off += 8;

    // product_name
    if data.len() < off + 4 {
        return Err(VerifyError::InvalidFormat("product name length truncated".into()));
    }
    let name_len = u32::from_le_bytes(data[off..off + 4].try_into().unwrap()) as usize;
    off += 4;
    if data.len() < off + name_len {
        return Err(VerifyError::InvalidFormat("product name truncated".into()));
    }
    let product_name = String::from_utf8(data[off..off + name_len].to_vec())
        .map_err(|e| VerifyError::InvalidFormat(format!("invalid UTF-8 product name: {}", e)))?;
    off += name_len;

    // expiry_timestamp
    if data.len() < off + 8 {
        return Err(VerifyError::InvalidFormat("expiry timestamp truncated".into()));
    }
    let expiry_timestamp = i64::from_le_bytes(data[off..off + 8].try_into().unwrap());

    Ok(LicenseInfo {
        hardware_id,
        apply_timestamp,
        product_name,
        expiry_timestamp,
    })
}

/// Verify a license code using a public key.
///
/// # Arguments
/// * `public_key_bytes` - The contents of the `public_key.bin` file (BCRYPT_ECCPUBLIC_BLOB format)
/// * `license_code` - The Base64-encoded license code string
///
/// # Returns
/// The verified `LicenseInfo` on success, or a `VerifyError` on failure.
pub fn verify_license(public_key_bytes: &[u8], license_code: &str) -> Result<LicenseInfo, VerifyError> {
    // 1. Parse public key
    let verifying_key = parse_public_key(public_key_bytes)?;

    // 2. Base64 decode the license code
    let data = base64::engine::general_purpose::STANDARD
        .decode(license_code.trim())
        .map_err(|e: base64::DecodeError| VerifyError::Base64Error(e.to_string()))?;

    // 3. Parse binary format: dataLen(4) + data + signature
    if data.len() < 4 {
        return Err(VerifyError::InvalidFormat("data too short".into()));
    }
    let dl = u32::from_le_bytes(data[0..4].try_into().unwrap()) as usize;
    // ECDSA P-256 raw signature is 64 bytes (R||S, 32 bytes each)
    if data.len() < 4 + dl + 64 {
        return Err(VerifyError::InvalidFormat("data truncated".into()));
    }

    let license_data = &data[4..4 + dl];
    let sig_bytes = &data[4 + dl..4 + dl + 64];

    // 4. SHA-256 hash of license data
    let mut hasher = Sha256::new();
    hasher.update(license_data);
    let hash = hasher.finalize();

    // 5. ECDSA verify signature (raw R||S format, 32+32=64 bytes)
    use p256::ecdsa::signature::hazmat::PrehashVerifier;
    let mut r_bytes = [0u8; 32];
    let mut s_bytes = [0u8; 32];
    r_bytes.copy_from_slice(&sig_bytes[0..32]);
    s_bytes.copy_from_slice(&sig_bytes[32..64]);
    let signature = Signature::from_scalars(r_bytes, s_bytes)
        .map_err(|e| VerifyError::SignatureError(format!("invalid signature: {}", e)))?;
    verifying_key.verify_prehash(&hash, &signature)
        .map_err(|e| VerifyError::SignatureError(format!("verification failed: {}", e)))?;

    // 6. Deserialize license data
    deserialize_license(license_data)
}

/// Convenience function: verify a license code using a public key file path.
///
/// # Arguments
/// * `public_key_path` - Path to the `public_key.bin` file
/// * `license_code` - The Base64-encoded license code string
#[cfg(feature = "std")]
pub fn verify_license_from_file(
    public_key_path: &std::path::Path,
    license_code: &str,
) -> Result<LicenseInfo, VerifyError> {
    let pub_key_bytes = std::fs::read(public_key_path)
        .map_err(|e| VerifyError::InvalidPublicKey(format!("cannot read public key file: {}", e)))?;
    verify_license(&pub_key_bytes, license_code)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_public_key_rejects_short_blob() {
        let result = parse_public_key(&[0u8; 4]);
        assert!(result.is_err());
    }

    #[test]
    fn test_parse_public_key_rejects_wrong_magic() {
        let mut blob = vec![0u8; 72];
        blob[0..4].copy_from_slice(&0x12345678u32.to_le_bytes());
        let result = parse_public_key(&blob);
        assert!(result.is_err());
    }

    #[test]
    fn test_verify_rejects_invalid_base64() {
        let result = verify_license(&[0u8; 72], "!!!invalid!!!");
        assert!(result.is_err());
    }

    #[test]
    fn test_verify_rejects_short_data() {
        let result = verify_license(&[0u8; 72], "AAAA");
        assert!(result.is_err());
    }
}
